### ISSUE TITLE
Add Managed Identities support in ARO

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/OpenShift#219]
@sakthi-vetrivel @kagowda

**Comment by ezYakaEagle442** [comment]
@rahug1190 could you add an update on this please ?

**Comment by ezYakaEagle442** [comment]
FYI [AWS ROSA uses STS](https://docs.openshift.com/rosa/rosa_getting_started_sts/rosa-sts-getting-started-workflow.html) tokens

**Comment by stephensabeygov** [comment]
An update on this would be appreciated

**Comment by Rajan-Gupta1** [comment]
@sakthi-vetrivel Using Azure KeyVault with Red-hot OpenShift and then using Service Principal to connect to KeyVault and storing the secret in K8 Secrets is another level of indirection which is not security. Can you advise if RedHat will support managed identities as it is technically possible or not? if not technically possible let your customers know so we can determine better options

**Comment by stephensabeygov** [comment]
Will this backlog item be updated to indicate support for "Azure Workload Identity"? (https://github.com/Azure/azure-workload-identity)

**Comment by nagpradis** [comment]
Looks like ARO does not support Managed Identities yet. Any update on this please?

**Comment by trdrake-tw** [comment]
So, it's been about a year and a half since this was added to the roadmap (more specifically: was created and had a tag attached).  Can we get an update, please? As @Rajan-Gupta1 notes, current workarounds are not fully secure. And AKS supports MIs...

**Comment by trdrake-tw** [comment]
> Will this backlog item be updated to indicate support for "Azure Workload Identity"? (https://github.com/Azure/azure-workload-identity)
see https://github.com/Azure/OpenShift/issues/249

**Comment by stephensabeygov** [comment]
Thanks for the link to #249 - I had not realized that it was created and is actually In Progress! That is great news, but shouldn't this  issue be closed now with an indication that support for Managed Identities will be added through Azure Workload Identity?

**Comment by trdrake-tw** [comment]
Personally, I would agree ;)

**Comment by mtangtir** [comment]
May I know any progress on this?

**Comment by AnandKatta** [comment]
May i know the progress

**Comment by jboutaud** [comment]
This feature is in development with the development of 4.14 @0kashi would you mind adding some details on the feature and goals that we driving towards?

**Comment by AnandKatta** [comment]
Please provide some reference links for the implementation

**Comment by 0kashi** [comment]
Implementation documents are currently unavailable as the feature is not yet available. Nevertheless, Azure Red Hat OpenShift intends to employ workload identities within the cluster while also extending this capability to customer workloads. This new architecture won't rely on Service Principals. Instead, core cluster operators will utilize user-assigned managed identities and workload identity federation to acquire short-term credentials. To support customer workloads, we expect the process to be to create a managed identity with a federated identity credential in the cluster's tenant, which includes the OIDC issuerURL, and [set the annotation on the workload's service account](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html#service-account).

We anticipate offering a preview of this functionality in early 2024.

It's important to note that this change will not impact existing clusters, and the ability to create Service Principal-based clusters will remain unchanged. This feature just introduces the option to create additional clusters using managed identities instead of Service Principals.

*Please be aware that timelines and forward-looking statements are subject to change.

**Comment by mqasimsarfraz** [comment]
@0kashi  Is this feature available for preview? Mainly I want to disable the `Allow storage account key access` used by both the storage accounts created by ARO. Is this the right functionality for it or there is already a way to disable access via shared key access?

**Comment by 0kashi** [comment]
@mqasimsarfraz - This feature is undergoing active development and is not currently available as preview.

**Comment by davidkarlsen** [comment]
?

**Comment by 0kashi** [comment]
This feature is now in preview: https://learn.microsoft.com/en-us/azure/openshift/howto-understand-managed-identities

**Comment by vermacodes** [comment]
We've been eagerly awaiting the Managed Identity feature for ARO, especially because in the standard flow, a new service principal is created in AAD. That step requires the identity running `az aro create` to have privileges to create service principals.

For automation scenarios, this has been a blocker. Previously, the identity needed **write** access to AAD. Now, even with Managed Identity enabled, it still requires **read** access to AAD, specifically to query service principals during validation.

This means the identity used to create the cluster must still have elevated AAD permissions, which introduces risk in larger, security-conscious environments. We deploy many other Azure resources without needing this level of access, only ARO demands it, seemingly for internal validation.

Here’s the command we’re running:

```bash
az aro create \
  --resource-group default-jeeu-rg \
  --subscription [SUBSCRIPTION_ID] \
  --name default-jeeu-aro-0 \
  --vnet default-jeeu-vnet \
  --master-subnet ...AROMasterSubnet \
  --worker-subnet ...AROWorkerSubnet \
  --version 4.15.35 \
  --enable-managed-identity \
  --assign-cluster-identity ...default-jeeu-uai-aro-cluster-0 \
  --assign-platform-workload-identity file-csi-driver ... \
  --assign-platform-workload-identity cloud-controller-manager ... \
  --assign-platform-workload-identity ingress ... \
  --assign-platform-workload-identity image-registry ... \
  --assign-platform-workload-identity machine-api ... \
  --assign-platform-workload-identity cloud-network-config ... \
  --assign-platform-workload-identity aro-operator ... \
  --assign-platform-workload-identity disk-csi-driver ... \
  --debug
```

And here’s the error we’re hitting:

```
GraphError: Insufficient privileges to complete the operation.
Authorization_RequestDenied: Insufficient privileges to complete the operation.
```

This seems to stem from a GET request to `/servicePrincipals` during validation, which fails due to lack of AAD read access.

For Managed Identity to be truly usable in automated workflows, this dependency on AAD permissions needs to be reconsidered. Ideally, users should be able to deploy ARO clusters without requiring elevated access to AAD, especially when all identities are pre-assigned and scoped correctly.

We’d love to see this addressed to enable broader adoption and safer automation.

Complete Error

```
az aro create \
         --resource-group default-jeeu-rg \
         --subscription [SUBSCRIPTION_ID] \
         --name default-jeeu-aro-0 \
         --vnet default-jeeu-vnet \
         --master-subnet /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.Network/virtualNetworks/default-jeeu-vnet/subnets/AROMasterSubnet \
         --worker-subnet /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.Network/virtualNetworks/default-jeeu-vnet/subnets/AROWorkerSubnet \
         --version 4.15.35 \
         --enable-managed-identity \
         --assign-cluster-identity /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/default-jeeu-uai-aro-cluster-0 \
         --assign-platform-workload-identity file-csi-driver /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/default-jeeu-uai-file-csi-driver-0 \
         --assign-platform-workload-identity cloud-controller-manager /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/default-jeeu-uai-cloud-controller-manager-0 \
         --assign-platform-workload-identity ingress /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/default-jeeu-uai-ingress-0 \
         --assign-platform-workload-identity image-registry /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/default-jeeu-uai-image-registry-0 \
         --assign-platform-workload-identity machine-api /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/default-jeeu-uai-machine-api-0 \
         --assign-platform-workload-identity cloud-network-config /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/default-jeeu-uai-cloud-network-config-0 \
         --assign-platform-workload-identity aro-operator /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/default-jeeu-uai-aro-operator-0 \
         --assign-platform-workload-identity disk-csi-driver /subscriptions/[SUBSCRIPTION_ID]/resourceGroups/default-jeeu-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/default-jeeu-uai-disk-csi-driver-0 \
       --debug
 ': exit status 1. Output: t = self._send("GET", "/servicePrincipals" + _filter_to_query(filter))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 60, in _send
     raise GraphError(ex.response.json()['error']['message'], ex.response) from ex
 azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Insufficient privileges to complete the operation.

 ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
 ERROR: az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
 ERROR: cli.azure.cli.core.azclierror: Insufficient privileges to complete the operation.
 Traceback (most recent call last):
   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 57, in _send
     r = send_raw_request(self._cli_ctx, method, url, resource=self._resource, uri_parameters=param,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/util.py", line 1010, in send_raw_request
     raise HTTPError(reason, r)
 azure.cli.core.azclierror.HTTPError: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the
 operation.","innerError":{"date":"2025-09-08T17:13:21","request-id":"[CLIENT_REQUEST_ID]","client-request-id":"[CLIENT_REQUEST_ID]"}}})

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
     cmd_result = self.invocation.execute(args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
     raise ex
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
     results.append(self._run_job(expanded_arg, cmd_copy))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
     result = cmd_copy(params)
              ^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
     return self.handler(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
     return op(**command_args)
            ^^^^^^^^^^^^^^^^^^
   File "/root/.azure/cliextensions/aro/azext_aro/custom.py", line 98, in aro_create
     validate(cmd,
   File "/root/.azure/cliextensions/aro/azext_aro/custom.py", line 262, in validate
     rp_client_sp_id = aad.get_service_principal_id(resolve_rp_client_id())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/.azure/cliextensions/aro/azext_aro/_aad.py", line 31, in get_service_principal_id
     sps = self.client.service_principal_list(f"appId eq '{app_id}'")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 184, in service_principal_list
     result = self._send("GET", "/servicePrincipals" + _filter_to_query(filter))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 60, in _send
     raise GraphError(ex.response.json()['error']['message'], ex.response) from ex
 azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Insufficient privileges to complete the operation.
 ERROR: az_command_data_logger: Insufficient privileges to complete the operation.
 Traceback (most recent call last):
   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 57, in _send
     r = send_raw_request(self._cli_ctx, method, url, resource=self._resource, uri_parameters=param,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/util.py", line 1010, in send_raw_request
     raise HTTPError(reason, r)
 azure.cli.core.azclierror.HTTPError: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the
 operation.","innerError":{"date":"2025-09-08T17:13:21","request-id":"[CLIENT_REQUEST_ID]","client-request-id":"[CLIENT_REQUEST_ID]"}}})

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
     cmd_result = self.invocation.execute(args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
     raise ex
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
     results.append(self._run_job(expanded_arg, cmd_copy))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
     result = cmd_copy(params)
              ^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
     return self.handler(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
     return op(**command_args)
            ^^^^^^^^^^^^^^^^^^
   File "/root/.azure/cliextensions/aro/azext_aro/custom.py", line 98, in aro_create
     validate(cmd,
   File "/root/.azure/cliextensions/aro/azext_aro/custom.py", line 262, in validate
     rp_client_sp_id = aad.get_service_principal_id(resolve_rp_client_id())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/.azure/cliextensions/aro/azext_aro/_aad.py", line 31, in get_service_principal_id
     sps = self.client.service_principal_list(f"appId eq '{app_id}'")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 184, in service_principal_list
     result = self._send("GET", "/servicePrincipals" + _filter_to_query(filter))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 60, in _send
     raise GraphError(ex.response.json()['error']['message'], ex.response) from ex
 azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Insufficient privileges to complete the operation.
 To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
 DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x72cf7ce0ae80>]
 INFO: az_command_data_logger: exit code: 1
 INFO: cli.__main__: Command ran in 2.784 seconds (init: 0.223, invoke: 2.561)
 INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
 INFO: telemetry.client: Accumulated 0 events. Flush the clients.
 INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
 INFO: telemetry.save: Save telemetry record of length 8765 in cache file under /root/.azure/telemetry/20250908171322259
 INFO: telemetry.main: Begin creating telemetry upload process.
 INFO: telemetry.process: Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.12/site-packages/azure/cli/telemetry/__init__.py /root/.azure
 /root/.azure/telemetry/20250908171322259"
 INFO: telemetry.process: Return from creating process 1505
 INFO: telemetry.main: Finish creating telemetry upload process.
```

**Comment by 0kashi** [comment]
@vermacodes - Thank you for raising this.  This seems to be related to remnants of a Service Principal based cluster which shouldn't be needed.  This will be addressed and you can see a correlated pull request for addressing it.

**Comment by Honken77** [comment]
Any way to test this out with the AzureRM terraform provider? We don't provision any clusters with az cli, not even our own test clusters.

**Comment by ezYakaEagle442** [comment]
Hi,
I am happy to see it is GA now : [https://learn.microsoft.com/en-us/azure/openshift/howto-understand-managed-identities](https://learn.microsoft.com/en-us/azure/openshift/howto-understand-managed-identities).

**Comment by davidkarlsen** [comment]
Will you support it in https://github.com/hashicorp/terraform-provider-azurerm/issues/31691 as well?
