### ISSUE TITLE
az openshift show not working

### ISSUE THREAD

**Issue by jim-minter** [Azure/OpenShift#32]
```
# az openshift show --resource-group X --name Y
'NoneType' object has no attribute 'peer_vnet_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 701, in handler
    show_exception_handler(ex)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 711, in show_exception_handler
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 699, in handler
    return getter(**args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2368, in openshift_show
    return _remove_osa_nulls([mc])
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2257, in _remove_osa_nulls
    delattr(managed_cluster.network_profile, attr)
AttributeError: 'NoneType' object has no attribute 'peer_vnet_id'
```

**Comment by jim-minter** [comment]
@julienstroheker @amanohar @cjryan I'm guessing discrepancy between latest CLI docker image and the rolled out API version.

**Comment by jim-minter** [comment]
@julienstroheker are you able to fix in the CLI in the short term out of interest?

**Comment by julienstroheker** [comment]
@jim-minter Thanks for the catch. It was related to the api version on the cli. 
Should be fixed now.

**Comment by thanasisk** [comment]
as of today 11:00 berlin time
➜  ~ docker pull julienstroheker/osa-cli:latest
latest: Pulling from julienstroheker/osa-cli
ff3a5c916c92: Already exists 
471170bb1257: Already exists 
d487cc70216e: Already exists 
9358b3ca3321: Already exists 
d4d73eb5841d: Already exists 
087422e22562: Already exists 
e917a8fee454: Pull complete 
07c266bfbb64: Pull complete 
0dd99949e20d: Pull complete 
Digest: sha256:863ec77753d7d1c5b0eecbadb21d38bbe07a60eae7a2329f315083a62256af58
Status: Downloaded newer image for julienstroheker/osa-cli:latest
➜  ~ docker run -it --rm julienstroheker/osa-cli:latest /bin/bash
[SNIP LOGIN DETAILS]
bash-4.4# az openshift show --name athanasioseu1 --resource-group athanasioseu
'NoneType' object has no attribute 'peer_vnet_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 701, in handler
    show_exception_handler(ex)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 711, in show_exception_handler
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 699, in handler
    return getter(**args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2368, in openshift_show
    return _remove_osa_nulls([mc])
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2257, in _remove_osa_nulls
    delattr(managed_cluster.network_profile, attr)
AttributeError: 'NoneType' object has no attribute 'peer_vnet_id'

**Comment by mjudeikis** [comment]
@jim-minter  ^ same error was on my side just I created new cluster for this test

**Comment by julienstroheker** [comment]
This is because my CLI is using the new version of the RP with the vnet peering option. 
I'll remove that part and wait for the new RP to be rollout in prod.

**Comment by julienstroheker** [comment]
I removed the `peer_vnet_id` field from the show command, should work now with any version of the RP.

**Comment by julienstroheker** [comment]
@jim-minter @mjudeikis can you validate on your side if you still have the issue ? Thanks

**Comment by julienstroheker** [comment]
Closing for now, should be fixed. Feel free to re-open if you still seeing this.
