### ISSUE TITLE
openshiftmanagedcluster feature register always in Pending state

### ISSUE THREAD

**Issue by fernandoBRS** [Azure/OpenShift#88]
I've been following the [known issues](https://github.com/Azure/OpenShift/blob/master/docs/known-issues.md#providers-and-features-must-be-registered-manually) steps and I'm having issues on registering the `openshiftmanagedcluster` feature, because it's always in Pending state. These are the steps I've been doing:

```
az feature register --namespace Microsoft.ContainerService -n openshiftmanagedcluster
```

Then checking the status:

```
az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/openshiftmanagedcluster')].{Name:name,State:properties.state}"
```

This is the output:

```
Name                                                State
--------------------------------------------------  -------
Microsoft.ContainerService/openshiftmanagedcluster  Pending
```

I followed the steps to register the `Microsoft.Solutions` and `Microsoft.Network` and refresh the `Microsoft.ContainerService`, but openshiftmanagedcluster is still in Pending state.

I'm using az cli `v2.0.60` on WSL and Python 3.6.5.

This issue brought another one for me: I can't connect to any AKS cluster. Any `az aks` command I use, I receive the following error:

```
cannot import name 'OpenShiftManagedClusterAgentPoolProfile'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 251, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 266, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 143, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 455, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 495, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 61, in <module>
    from azure.mgmt.containerservice.models import OpenShiftManagedClusterAgentPoolProfile
ImportError: cannot import name 'OpenShiftManagedClusterAgentPoolProfile'
```

**Comment by sozercan** [comment]
@fernandoBRS is your subscription whitelisted for OSA?

**Comment by amanohar** [comment]
@fernandoBRS please email us your subscription id so we can whitelist it.
cc: @jimzim

**Comment by fernandoBRS** [comment]
@sozercan @amanohar I just sent out an email to be whitelisted. Thank you!

**Comment by amanohar** [comment]
Closing as the issue has been resolving by registering the subscription with a required feature flag.
